project:
  type: website
  output-dir: docs

website:
  title: "Seminario de investigación - Grupos 47 y 88"
  navbar:
    left:
      - href: index.qmd
        text: Home
      #- href: syllabus.qmd
      #  text: Syllabus

format:
  html:
    theme: cosmo
    toc: true
