project:
  type: website
  output-dir: docs

website:
  title: "Seminario de investigación - Grupos 35 y 36"
  navbar:
    left:
      - href: index.qmd
        text: Inicio

format:
  html:
    theme: cosmo
    toc: true
